env:
  jest: true
  node: true
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser:
  babel-eslint
rules:
  no-console: 0
plugins:
  - jest
  - babel